
[functions.admin-pilot-action]
enabled = true
verify_jwt = true
import_map = "./functions/admin-pilot-action/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-pilot-action/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-pilot-action/*.html" ]

[functions.calculate-trust-score]
enabled = true
verify_jwt = true
import_map = "./functions/calculate-trust-score/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calculate-trust-score/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calculate-trust-score/*.html" ]

[functions.dispute-engine]
enabled = true
verify_jwt = true
import_map = "./functions/dispute-engine/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/dispute-engine/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/dispute-engine/*.html" ]
