server {
    listen 5050;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Gzip compression for better performance
    gzip on;
    gzip_types text/plain text/css text/javascript application/json;
}
